services:
  mongodb:
    image: mongo:latest
    container_name: blog-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123
    volumes:
      - blog-data:/data/db

volumes:
  blog-data:
